const TEST_ALIASES = {
  'cbc': ['complete blood count'],
  'crp': ['c-reactive protein', 'c reactive protein'],
  'sgpt': ['alt', 'alanine aminotransferase'],
  'sgot': ['ast', 'aspartate aminotransferase'],
  'lft': ['liver function test'],
  'kft': ['kidney function test'],
  'rft': ['renal function test'],
  'tft': ['thyroid function test'],
  'lipid': ['lipid profile'],
  'fbs': ['fasting blood sugar'],
  'ppbs': ['post prandial blood sugar'],
  'hba1c': ['glycated hemoglobin', 'glycosylated hemoglobin', 'hb1ac', 'hba1 c'],
  'tsh': ['thyroid stimulating hormone'],
  't3': ['triiodothyronine'],
  't4': ['thyroxine'],
  'esr': ['erythrocyte sedimentation rate'],
  'bun': ['blood urea nitrogen'],
  'wbc': ['white blood cell count', 'total leucocyte count', 'tlc'],
  'rbc': ['red blood cell count'],
  'plt': ['platelet count'],
  'ecg': ['electrocardiogram', 'ekg'],
  'usg': ['ultrasound', 'ultrasonography'],
  'mri': ['magnetic resonance imaging'],
  'ct': ['computed tomography'],
  'xray': ['x-ray', 'radiograph'],
  'rtpcr': ['rt-pcr', 'reverse transcription polymerase chain reaction'],
  'hiv': ['human immunodeficiency virus'],
  'hcv': ['hepatitis c virus'],
  'hbsag': ['hepatitis b surface antigen'],
  'vdrl': ['venereal disease research laboratory'],
  'tmt': ['treadmill test'],
  'pft': ['pulmonary function test'],
  'eeg': ['electroencephalogram'],
  'dexa': ['dual-energy x-ray absorptiometry', 'bone mineral density'],
  'pap': ['papanicolaou smear'],
  'fnac': ['fine needle aspiration cytology'],
  'culture': ['c/s', 'culture and sensitivity'],
  'urine rm': ['urine routine microscopy', 'urine r/m', 'urine routine'],
};
